openapi: 3.0.0
info:
  title: Life Dashboard - golfTracker
  description: The golfTracker app for the Life Dashboard
  version: 0.0.0
paths:
  /healthcheck:
    get:
      summary: Returns a health check for the golfTracker app.
      description: A health check for the golfTracker app
      responses:
        '200':
          description: golfTracking api is running
components:
  schemas:
    GolfRound:
      type: object
        properties:
          id:
            type: integer
            format: int64
          courseName:
            type: string
          datetime:
            type: string
            format: date-time
          holes:
            type: array
            items: 
              $ref: '#components/schemas/GolfRoundHole'
    GolfRoundHole:
      type: object
        properties:
          id:
            type: integer
            format: int64
          par:
            type: number
            format: double
          strokeIndex:
            type: number
            format: double
          score:
            type: number
            format: double
    DrivingRangeSession:
      type: object
        properties:
          id:
            type: integer
            format: int64
          shots:
            type: array
            items: 
              $ref: '#components/schemas/DrivingRangeSessionShot'
    DrivingRangeSessionShot:
      type: object
        properties:
          id:
            type: integer
            format: int64
          club:
            type: string
          distance:
            type: number
            format: double
          meta:
            type: string